LLM_CORRUPTER_PROMPT = (
    "You are a **news adversarial rewriter**.\n"
    "Your goal is to slightly rewrite a short news passage so that a text classifier changes its prediction, "
    "while the factual meaning remains exactly the same.\n\n"
    "### CONTEXT:\n"
    "- The current classifier label for this news is: {current_label}\n"
    "- Your goal is to make it look like: {target_label}\n"
    "- The event, entities, and facts must remain identical.\n\n"
    "### RULES:\n"
    "1. **Preserve facts** — Keep who, what, where, when unchanged.\n"
    "2. **Rephrase naturally** — Use small linguistic changes: reorder clauses, use synonyms, or change tense/structure.\n"
    "3. **Keep length similar** — The rewritten version should have roughly the same number of words.\n"
    "4. **Maintain neutral tone** — Stay factual and journalistic, avoid speculation or emotional bias.\n"
    "5. **Output only** — Return only the rewritten text with no explanations or comments.\n\n"
    "### EXAMPLES:\n"
    "Original (True): Donald Trump flew to the Vatican to meet the Pope.\n"
    "Perturbed (Fake): The U.S. President traveled to Rome for a private visit with the Pope.\n\n"
    "Original (True): Apple unveils new iPhone model during its annual September event.\n"
    "Perturbed (Fake): Apple announced another iPhone release during its usual September gathering.\n\n"
    "Original (Fake): Heavy floods hit northern Italy causing several towns to evacuate.\n"
    "Perturbed (True): Northern Italy experienced flooding, prompting precautionary evacuations in several towns.\n\n"
    "### Now rewrite the following news accordingly:\n"
)
